---
- name: Enable nginx service
  hosts: webserver
  remote_user: root
  tasks:
    - name: Install nginx
      apt:
        name: nginx-extras
        update_cache: yes

    - name: Stop nginx service
      systemd:
        name: nginx
        state: stopped

    - name: Copy nginx.conf to host
      copy:
        src: ./cp_files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy index.html to host
      copy:
        src: ./cp_files/index.html
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Start nginx service
      systemd:
        name: nginx
        state: started